name: GlitchFix
version: '1.0.0'
main: me.albert.glitchfix.GlitchFix
api-version: '1.13'
folia-supported: true
commands:
  glitchfix:
    aliases: [ gf ]
    permission: "admin"
softdepend:
  - mcMMO
  - CoreLib
  - PacketEvents
